<Document accessor="public" category="Function" name="GetFailure" declFile="WfLibraryPredefined.h" declId="FB$vl::reflection::description::ICoroutine::GetFailure@::vl::Ptr&lt;::vl::reflection::description::IValueException&gt;()[decl0]"><summary>Returns the current exception.</summary><returns>The current exception. It could cause by the Workflow script that creates this coroutine, or by calling <symbol name="Resume" docId="vl::reflection::description::ICoroutine::Resume@void(bool, ::vl::Ptr&lt;::vl::reflection::description::CoroutineResult&gt;)" declFile="WfLibraryPredefined.h" declId="FB$vl::reflection::description::ICoroutine::Resume@void(bool, ::vl::Ptr&lt;::vl::reflection::description::CoroutineResult&gt;)[decl0]"/> when this coroutine is in an inappropriate state.</returns><signature><![CDATA[Ptr<IValueException> GetFailure(
);
]]></signature><seealsos><symbol name="Ptr" docId="vl::Ptr" declFile="Pointer.h" declId="NI$vl::Ptr"/><symbol name="IValueException" declFile="GuiTypeDescriptorPredefined.h" declId="NI$vl::reflection::description::IValueException"/></seealsos></Document>